Repository astarte-platform/astarte-dashboard, pull requests merged in 2020-12, with the labels that each got.

#248 Fix app crashing when Flow is disabled in the app's config
  cypress/fixtures/config/flowDisabled.json
  cypress/integration/login_test.js
  src/elm/Main.elm
  src/react/HomePage.jsx
  src/react/SessionManager.js
Labels: bug

#234 Add Confirm and Form modal components
  cypress/integration/block_page_test.js
  cypress/integration/pipeline_page_test.js
  cypress/integration/register_device_page_test.js
  src/react/BlockSourcePage.tsx
  src/react/FlowInstancesPage.tsx
  src/react/GroupDevicesPage.tsx
  src/react/NewPipelinePage.tsx
  src/react/PipelineSourcePage.tsx
  src/react/RealmSettingsPage.tsx
  src/react/RegisterDevicePage.tsx
  src/react/components/modals/Confirm.tsx
  src/react/components/modals/Form.tsx
Labels: enhancement

#241 Fix tables responsiveness
  cypress/integration/interface_value_page_test.js
  src/elm/Page/Device.elm
  src/elm/Ui/TriggerActionEditor.elm
  src/react/DeviceInterfaceValues.jsx
Labels: enhancement

#243 Add independent scrolling behaviors for sidebar and content
  cypress/integration/device_page_test.js
  src/elm/Main.elm
Labels: user experience

#242 Update routing for React views
  cypress/fixtures/group.special-characters.devices.json
  cypress/fixtures/groups.json
  cypress/integration/group_page_test.js
  cypress/integration/groups_page_test.js
  cypress/integration/interface_builder_test.js
  cypress/integration/trigger_builder_test.js
  package-lock.json
  package.json
  src/react/BlockSourcePage.tsx
  src/react/BlocksPage.tsx
  src/react/DevicesPage.tsx
  src/react/FlowConfigurationPage.tsx
  src/react/FlowInstancesPage.tsx
  src/react/GroupDevicesPage.tsx
  src/react/GroupsPage.tsx
  src/react/HomePage.jsx
  src/react/InterfacesPage.tsx
  src/react/LoginPage.tsx
  src/react/NewBlockPage.tsx
  src/react/NewGroupPage.tsx
  src/react/NewPipelinePage.tsx
  src/react/PipelineSourcePage.tsx
  src/react/PipelinesPage.tsx
  src/react/RealmSettingsPage.tsx
  src/react/RegisterDevicePage.tsx
  src/react/Router.jsx
  src/react/TriggersPage.tsx
Labels: minor

#249 Add tests for live error messages in Device page
  cypress/integration/device_page_test.js
Labels: testing

#245 Fix typo in SessionManager's setup
  cypress/fixtures/config/custom_urls.json
  cypress/integration/login_test.js
  src/react/SessionManager.js
Labels: bug

#252 Forward port release-1.0 into master
  cypress/fixtures/config/custom_urls.json
  cypress/fixtures/config/flowDisabled.json
  cypress/fixtures/group.special-characters.devices.json
  cypress/fixtures/groups.json
  cypress/integration/block_page_test.js
  cypress/integration/device_page_test.js
  cypress/integration/group_page_test.js
  cypress/integration/groups_page_test.js
  cypress/integration/interface_builder_test.js
  cypress/integration/interface_value_page_test.js
  cypress/integration/login_test.js
  cypress/integration/pipeline_page_test.js
  cypress/integration/register_device_page_test.js
  cypress/integration/trigger_builder_test.js
  package-lock.json
  package.json
  src/elm/AstarteApi.elm
  src/elm/Main.elm
  src/elm/Page/Device.elm
  src/elm/Page/TriggerBuilder.elm
  src/elm/Types/RealmConfig.elm
  src/elm/Types/Session.elm
  src/elm/Types/Trigger.elm
  src/elm/Ui/Card.elm
  src/elm/Ui/TriggerActionEditor.elm
  src/react/BlockSourcePage.tsx
  src/react/BlocksPage.tsx
  src/react/DeviceInterfaceValues.tsx
  src/react/DevicesPage.tsx
  src/react/FlowConfigurationPage.tsx
  src/react/FlowInstancesPage.tsx
  src/react/GroupDevicesPage.tsx
  src/react/GroupsPage.tsx
  src/react/HomePage.jsx
  src/react/InterfacesPage.tsx
  src/react/LoginPage.tsx
  src/react/NewBlockPage.tsx
  src/react/NewGroupPage.tsx
  src/react/NewPipelinePage.tsx
  src/react/PipelineSourcePage.tsx
  src/react/PipelinesPage.tsx
  src/react/RealmSettingsPage.tsx
  src/react/RegisterDevicePage.tsx
  src/react/Router.jsx
  src/react/SessionManager.js
  src/react/TriggersPage.tsx
  src/react/components/modals/Confirm.tsx
  src/react/components/modals/Form.tsx
Labels: chore

#246 Enhance AstarteToken validation
  src/astarte-client/client.ts
  src/astarte-client/models/Token/index.ts
  src/astarte-client/types/index.ts
  src/astarte-client/types/token.ts
  src/react/LoginPage.tsx
Labels: enhancement

#253 Fix app crashing when no config is supplied
  cypress/integration/interface_builder_test.js
  src/static/index.js
Labels: bug

#254 Double encode group names in Astarte API URLs
  cypress/integration/device_page_test.js
  cypress/integration/group_page_test.js
  src/astarte-client/client.ts
  src/elm/AstarteApi.elm
Labels: bug

#256 Add Cypress interaction tests for the Interface Editor
  cypress/fixtures/test.astarte.NoDefaultsInterface.json
  cypress/fixtures/test.astarte.SpecifiedDefaultsInterface.json
  cypress/integration/interface_builder_test.js
  elm.json
  src/elm/Modal/MappingBuilder.elm
  src/elm/Page/InterfaceBuilder.elm
  src/elm/Types/InterfaceMapping.elm
Labels: bug, testing
