Repository astarte-platform/astarte-dashboard, pull requests merged in 2020-01, with the labels that each got.

#11 Prepare 0.11.0-beta.1 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore

#16 Prepare 0.11.0-beta.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore

#17 Data triggers matching "Any interface"
  CHANGELOG.md
  package-lock.json
  package.json
  src/elm/Page/TriggerBuilder.elm
  src/elm/Types/DataTrigger.elm
Labels: bug, user experience

#18 DeviceData: add property value conversion
  CHANGELOG.md
  src/elm/Types/DeviceData.elm
Labels: bug

#21 InterfaceBuilder.elm: explicit_timestamp default true
  CHANGELOG.md
  src/elm/Page/InterfaceBuilder.elm
Labels: enhancement, user experience
