Repository astarte-platform/astarte-dashboard, pull requests merged in 2020-07, with the labels that each got.

#116 Home: fix service health labels
  CHANGELOG.md
  src/elm/Page/Home.elm
Labels: minor

#117 OAuth logout and re-login
  src/elm/Main.elm
  src/static/index.js
Labels: enhancement

#121 Fix browser url on page change
  src/elm/Main.elm
Labels: minor

#120 DevicesPage.js: fix device table pagination
  src/react/DevicesPage.js
Labels: minor

#123 Device.elm: show alias being deleted
  src/elm/Page/Device.elm
Labels: user experience

#124 Add support for groups in device triggers
  CHANGELOG.md
  src/elm/Page/TriggerBuilder.elm
  src/elm/Types/DeviceTrigger.elm
Labels: main feature

#115 Interface: consider hyphens as lowercase
  src/elm/Types/Interface.elm
Labels: minor

#122 TriggerBuilder: Fix datatrigger validation from source
  src/elm/Page/TriggerBuilder.elm
Labels: minor

#113 Improve device interface data page
  src/elm/Main.elm
  src/elm/Page/DeviceData.elm
  src/react/AstarteClient.js
  src/react/DeviceInterfaceValues.js
  src/react/Router.js
  src/react/ui/BackButton.js
Labels: enhancement

#125 Add initial introspection when registering devices
  CHANGELOG.md
  src/react/AstarteClient.js
  src/react/RegisterDevicePage.js
  src/static/styles/main.scss
Labels: main feature

#126 Move Triggers page from Elm to React
  src/elm/Main.elm
  src/elm/Page/Triggers.elm
  src/react/Router.js
  src/react/TriggersPage.js
Labels: chore

#127 Move Interfaces page from Elm to React
  src/elm/Main.elm
  src/elm/Page/Interfaces.elm
  src/react/InterfacesPage.js
  src/react/Router.js
Labels: chore

#129 TriggerBuilder: update placeholder regex
  CHANGELOG.md
  src/elm/Page/TriggerBuilder.elm
Labels: minor
