Repository astarte-platform/astarte-dashboard, pull requests merged in 2020-11, with the labels that each got.

#225 Remove unused Elm code
  src/elm/AstarteApi.elm
  src/elm/Main.elm
  src/elm/Page/Device.elm
  src/elm/Page/TriggerBuilder.elm
  src/elm/Types/RealmConfig.elm
  src/elm/Types/Session.elm
  src/elm/Types/Trigger.elm
  src/elm/Ui/Card.elm
Labels: chore

#227 Enhance Device model type and validation
  src/astarte-client/client.ts
  src/astarte-client/models/Device/index.ts
  src/astarte-client/transforms/device.ts
  src/astarte-client/transforms/index.ts
  src/astarte-client/types/dto/device.d.ts
  src/react/DeviceInterfaceValues.tsx
Labels: enhancement

#231 Add Typescript types for system and device live messages
  src/astarte-client/client.ts
  src/astarte-client/index.ts
  src/astarte-client/types/event.ts
  src/astarte-client/types/index.ts
Labels: enhancement

#239 Add a filter in Devices Page to get devices active since a specified date
  package-lock.json
  package.json
  src/react/DevicesPage.tsx
  webpack.dev.js
  webpack.prod.js
Labels: enhancement

#235 Add Device page tests to confirm modals with Enter
  cypress/integration/device_page_test.js
Labels: testing

#240 Add a Cypress test for active devices filter in Devices page
  cypress/integration/devices_page_test.js
  src/react/DevicesPage.tsx
Labels: enhancement

#237 Use tree structure to format interfaces data
  cypress/integration/interface_value_page_test.js
  src/astarte-client/client.ts
  src/astarte-client/index.ts
  src/astarte-client/models/Interface/index.ts
  src/astarte-client/models/Mapping/index.ts
  src/astarte-client/transforms/dataTree.ts
  src/astarte-client/transforms/index.ts
  src/astarte-client/types/dataType.ts
  src/astarte-client/types/interfaceValues.ts
  src/react/DeviceInterfaceValues.tsx
Labels: enhancement
