Repository astarte-platform/astarte-dashboard, pull requests merged in 2020-04, with the labels that each got.

#57 Prepare 0.11.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore

#49 Handle device info errors
  CHANGELOG.md
  src/elm/AstarteApi.elm
  src/elm/Page/Device.elm
Labels: bug, user experience

#53 Main.elm: editor-only navbar colors
  src/elm/Main.elm
Labels: user experience

#52 Add Pairing API health check
  CHANGELOG.md
  src/elm/AstarteApi.elm
  src/elm/Main.elm
Labels: enhancement, user experience

#59 index.js: remove workaround on socket URL
  src/static/index.js
Labels: chore

#58 Update dependencies and fix minimist
  package-lock.json
  package.json
Labels: chore, dependencies

#54 Aliases and metadata editing
  CHANGELOG.md
  src/elm/AstarteApi.elm
  src/elm/Icons.elm
  src/elm/Modal/AskKeyValue.elm
  src/elm/Modal/AskSingleValue.elm
  src/elm/Modal/ConfirmModal.elm
  src/elm/Page/Device.elm
  src/elm/Types/Device.elm
  src/static/styles/main.scss
Labels: main feature

#61 DevicesPage: Always show device registration link
  src/react/DevicesPage.js
Labels: bug, minor

#60 RegisterDevicePage: add UUIDv5 option
  src/react/Base64.js
  src/react/RegisterDevicePage.js
Labels: enhancement, user experience
