Repository astarte-platform/astarte-dashboard, pull requests merged in 2020-05, with the labels that each got.

#62 Add custom headers and HTTP method in triggers
  CHANGELOG.md
  src/elm/Page/TriggerBuilder.elm
  src/elm/Types/Trigger.elm
Labels: main feature

#65 Use monospace fonts in public key textareas
  CHANGELOG.md
  src/elm/Page/RealmSettings.elm
Labels: minor, user experience

#64 Use grey for "never connected" device
  src/elm/Page/Device.elm
  src/static/styles/main.scss
Labels: minor, user experience

#66 RegisterDevicePage: return to device list after registration
  src/react/RegisterDevicePage.js
Labels: minor, user experience

#63 index.js: Fix AppEngine endpoint URL
  src/static/index.js
Labels: blocking, bug

#67 Fix typos in Home
  src/elm/Page/Home.elm
Labels: minor, user experience

#69 Use monospace in device ID fields
  src/elm/Page/Device.elm
  src/react/DevicesPage.js
  src/react/GroupDevicesPage.js
  src/react/RegisterDevicePage.js
  src/react/astarte/Device.js
Labels: minor, user experience

#70 Replace request-promise with axios
  package-lock.json
  package.json
  src/react/AstarteClient.js
Labels: dependencies

#68 Typography adjustments
  src/elm/Page/Device.elm
  src/elm/Page/Home.elm
  src/elm/Page/InterfaceBuilder.elm
  src/elm/Ui/Card.elm
  src/static/styles/main.scss
Labels: minor, user experience

#71 InterfaceBuilder: minor style adjustments
  src/elm/Page/InterfaceBuilder.elm
  src/static/styles/main.scss
Labels: user experience

#72 Remove validation succesful icon
  src/static/styles/main.scss
Labels: user experience

#74 TriggerBuilder: allow placeholders in data trigger paths
  CHANGELOG.md
  src/elm/Page/TriggerBuilder.elm
Labels: bug, user experience

#79 Realm settings page cleanup
  src/elm/Page/RealmSettings.elm
Labels: user experience

#76 Home.elm: Add pairing API health icon
  src/elm/Page/Home.elm
Labels: user experience

#75 Home.elm: remove mascotte image
  src/elm/Assets.elm
  src/elm/Page/Home.elm
  src/static/img/homemascotte.svg
Labels: user experience

#78 Interface: set explicit timestamp when changing type to datastream
  CHANGELOG.md
  src/elm/Types/Interface.elm
Labels: user experience

#81 Gramar, color scheme and spacing fixes
  src/elm/Page/Device.elm
  src/elm/Page/InterfaceBuilder.elm
  src/elm/Page/Interfaces.elm
  src/elm/Page/Triggers.elm
  src/react/DevicesPage.js
  src/react/GroupDevicesPage.js
  src/react/GroupsPage.js
  src/react/NewGroupPage.js
  src/react/ui/CheckableDeviceTable.js
  src/react/ui/SingleCardPage.js
Labels: user experience

#80 Trigger builder layout and button adjustments
  src/elm/Page/TriggerBuilder.elm
Labels: user experience

#77 InterfaceBuilder: mapping type as badge
  src/elm/Page/InterfaceBuilder.elm
  src/elm/Types/InterfaceMapping.elm
Labels: user experience

#82 Date locale conversion via JS Ports
  src/elm/Page/Device.elm
  src/elm/Ports.elm
  src/static/index.js
Labels: user experience

#73 Use single application-wide Astarte client
  src/react/AstarteClient.js
  src/react/DevicesPage.js
  src/react/GroupDevicesPage.js
  src/react/GroupsPage.js
  src/react/NewGroupPage.js
  src/react/RegisterDevicePage.js
  src/react/Router.js
  src/static/index.js
Labels: enhancement

#84 Device stats table: Add Byte multiples and fix pie chart label positioning
  CHANGELOG.md
  src/elm/Page/Device.elm
  src/elm/Ui/PieChart.elm
  src/static/styles/main.scss
Labels: user experience

#85 Forward port from release v0.11
  CHANGELOG.md
  src/elm/Page/Device.elm
  src/elm/Page/Home.elm
  src/elm/Page/TriggerBuilder.elm
  src/elm/Ui/PieChart.elm
  src/static/styles/main.scss
Labels: chore

#83 Add login form validation
  CHANGELOG.md
  package-lock.json
  package.json
  src/elm/Main.elm
  src/elm/Page/Login.elm
  src/elm/Ports.elm
  src/static/index.js
Labels: user experience

#86 Prepare 0.11.1 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore
