Repository astarte-platform/astarte-dashboard, pull requests merged in 2020-10, with the labels that each got.

#183 Add Cypress tests for Blocks page
  cypress/fixtures/blocks.json
  cypress/fixtures/custom_block.json
  cypress/fixtures/native_block.json
  cypress/integration/block_page_test.js
  cypress/integration/blocks_page_test.js
  cypress/integration/new_block_page_test.js
Labels: enhancement, testing

#186 Add Cypress tests for Realm Settings page
  cypress/fixtures/config_auth.json
  cypress/integration/realm_settings_page_test.js
  src/react/RealmSettingsPage.jsx
Labels: enhancement, testing

#187 Add Cypress tests for Devices page
  cypress/fixtures/devices_detailed.json
  cypress/fixtures/devices_stats.json
  cypress/integration/devices_page_test.js
Labels: enhancement, testing

#188 Fix inconsistencies in Cypress tests
  cypress/fixtures/interfaces.json
  cypress/integration/device_page_test.js
  cypress/integration/devices_page_test.js
  cypress/integration/interface_builder_test.js
  cypress/integration/interfaces_page_test.js
  cypress/integration/register_device_page_test.js
  cypress/integration/trigger_builder_test.js
  cypress/integration/triggers_page_test.js
Labels: enhancement, testing

#190 Use a consistent login process in Cypress tests to prevent flakiness
  .github/workflows/functionality-tests.yml
  cypress/fixtures/user_config.json
  cypress/support/index.js
  package.json
  src/tools/generate-config-file.js
Labels: enhancement, testing

#191 Add Cypress tests for Groups page
  cypress/fixtures/group.first-floor.devices.json
  cypress/fixtures/group.test-devices.devices.json
  cypress/fixtures/groups.json
  cypress/integration/groups_page_test.js
  src/react/GroupsPage.jsx
Labels: enhancement, testing

#192 Add Cypress tests for Group page
  cypress/integration/group_page_test.js
Labels: enhancement, testing

#193 Add device filtering to the devices page
  CHANGELOG.md
  cypress/integration/devices_page_test.js
  src/react/DevicesPage.jsx
Labels: user experience

#195 Add Cypress tests for Pipelines page
  cypress/fixtures/pipeline.sample-computation.json
  cypress/fixtures/pipeline.test-calculation.json
  cypress/fixtures/pipelines.json
  cypress/integration/pipelines_page_test.js
Labels: Hacktoberfest, enhancement, testing

#202 Add Cypress tests for the sidebar
  cypress/integration/sidebar_test.js
Labels: Hacktoberfest, enhancement, testing

#199 Add Cypress tests for Flows page
  cypress/fixtures/flow.room1-occupation.json
  cypress/fixtures/flows.json
  cypress/integration/flows_page_test.js
Labels: Hacktoberfest, enhancement, testing

#197 Add Cypress tests for New Pipeline page
  .github/workflows/functionality-tests.yml
  cypress/integration/new_pipeline_page_test.js
  cypress/support/index.js
  package.json
  webpack.dev.js
Labels: Hacktoberfest, enhancement, testing

#194 Add Cypress tests for New Group page
  cypress/fixtures/group.first-floor.created.json
  cypress/integration/new_group_page.js
Labels: enhancement, testing

#196 Add Cypress tests for Pipeline page
  cypress/integration/pipeline_page_test.js
Labels: enhancement, testing

#189 Add Cypress tests for Home page
  cypress/integration/home_page_test.js
  src/react/HomePage.jsx
Labels: enhancement, testing

#200 Add Cypress tests for Flow page
  cypress/integration/flow_page_test.js
Labels: enhancement, testing

#201 Add Cypress tests for New Flow creation
  cypress/fixtures/pipeline.room-occupation.json
  cypress/integration/new_flow_page_test.js
  src/react/FlowConfigurationPage.jsx
Labels: enhancement, testing

#207 Filter devices by metadata
  cypress/integration/devices_page_test.js
  src/react/DevicesPage.jsx
  src/react/astarte/Device.js
  src/react/components/Highlight.jsx
Labels: user experience

#203 Interface.elm: good interface names may contain symbols
  src/elm/Types/Interface.elm
Labels: user experience

#168 Add types for Blocks
  .eslintrc.json
  package-lock.json
  package.json
  src/astarte-client/client.ts
  src/astarte-client/index.ts
  src/astarte-client/models/Block/CustomBlock.ts
  src/astarte-client/models/Block/NativeBlock.ts
  src/astarte-client/models/Block/index.ts
  src/astarte-client/models/Realm/index.ts
  src/astarte-client/models/Token/index.ts
  src/astarte-client/models/index.ts
  src/astarte-client/types/block.ts
  src/astarte-client/types/dto/block.d.ts
  src/astarte-client/types/dto/customBlock.d.ts
  src/astarte-client/types/dto/index.ts
  src/astarte-client/types/dto/nativeBlock.d.ts
  src/astarte-client/types/index.ts
  src/astarte-client/types/token.ts
  src/react/Base64.ts
  src/react/BlockSourcePage.jsx
  src/react/BlocksPage.jsx
  src/react/LoginPage.jsx
  src/static/index.js
  tsconfig.json
  webpack.common.js
Labels: chore, enhancement

#204 Update dependencies to fix vulnerabilities
  package-lock.json
  package.json
Labels: chore, dependencies

#170 Add typescript for block pages
  src/react/AlertManager.tsx
  src/react/BlockSourcePage.tsx
  src/react/BlocksPage.tsx
  src/react/NewBlockPage.tsx
  src/react/hooks/useInterval.ts
  src/react/hooks/useRelativeTime.ts
  src/react/types/index.ts
  src/react/types/timestamp.ts
  src/react/types/uuid.ts
  src/react/ui/BackButton.tsx
  src/react/ui/SingleCardPage.tsx
Labels: enhancement

#171 Add typescript for VisualEditor pages
  .eslintrc.json
  src/react/components/NativeBlockFactory.tsx
  src/react/components/NativeBlockWidget.tsx
  src/react/components/VisualFlowEditor.tsx
  src/react/models/NativeBlockModel.ts
Labels: enhancement

#205 Add typescript Device model
  src/astarte-client/index.ts
  src/astarte-client/models/Device/index.ts
  src/astarte-client/models/index.ts
  src/astarte-client/types/dto/device.d.ts
  src/astarte-client/types/dto/index.ts
  src/react/DeviceInterfaceValues.jsx
  src/react/DevicesPage.jsx
  src/react/GroupDevicesPage.jsx
  src/react/GroupsPage.jsx
  src/react/NewGroupPage.jsx
  src/react/astarte/Device.js
Labels: enhancement

#206 Move API data handling inside Astarte Client
  src/astarte-client/client.ts
  src/react/DeviceInterfaceValues.jsx
  src/react/DevicesPage.jsx
  src/react/FlowDetailsPage.jsx
  src/react/FlowInstancesPage.jsx
  src/react/GroupDevicesPage.jsx
  src/react/GroupsPage.jsx
  src/react/HomePage.jsx
  src/react/InterfacesPage.jsx
  src/react/NewGroupPage.jsx
  src/react/PipelineSourcePage.jsx
  src/react/PipelinesPage.jsx
  src/react/RealmSettingsPage.jsx
  src/react/RegisterDevicePage.jsx
  src/react/TriggersPage.jsx
  src/react/components/WaitForData.ts
  src/react/hooks/useFetch.ts
Labels: enhancement

#209 Move session handling from Elm to Javascript
  src/elm/AstarteApi.elm
  src/elm/Main.elm
  src/react/App.jsx
  src/react/Router.jsx
  src/react/SessionManager.js
  src/static/index.js
Labels: enhancement

#223 main.scss: fix device pie chart on Chrome
  CHANGELOG.md
  package-lock.json
  package.json
  src/elm/Page/Device.elm
  src/static/styles/main.scss
Labels: minor

#210 Add Typescript for Groups pages
  src/astarte-client/client.ts
  src/react/GroupDevicesPage.tsx
  src/react/GroupsPage.tsx
  src/react/NewGroupPage.tsx
  src/react/ui/CheckableDeviceTable.jsx
  src/react/ui/CheckableDeviceTable.tsx
  src/react/ui/SingleCardPage.tsx
Labels: enhancement

#212 Add typescript for Triggers page
  src/astarte-client/client.ts
  src/react/TriggersPage.tsx
Labels: enhancement

#214 Add typescript for Interfaces page
  src/astarte-client/client.ts
  src/react/InterfacesPage.tsx
Labels: enhancement

#224 Fix session protocol check
  cypress/fixtures/config/http.json
  cypress/fixtures/config/https.json
  cypress/integration/login_test.js
  cypress/support/index.js
  src/react/SessionManager.js
Labels: bug

#221 Add Cypress tests for Device Interface Values page
  cypress/fixtures/device_detailed.json
  cypress/fixtures/devices_detailed.json
  cypress/fixtures/group.first-floor.devices.json
  cypress/fixtures/group.test-devices.devices.json
  cypress/fixtures/interfaces.json
  cypress/fixtures/test.astarte.AggregatedObjectInterface.json
  cypress/fixtures/test.astarte.IndividualObjectInterface.json
  cypress/fixtures/test.astarte.ParametricObjectInterface.json
  cypress/fixtures/test.astarte.PropertiesInterface.json
  cypress/fixtures/test_aggregated_object_interface_values.json
  cypress/fixtures/test_individual_object_interface_values.json
  cypress/fixtures/test_parametric_object_aggregated_values.json
  cypress/fixtures/test_properties_interface_values.json
  cypress/integration/interface_value_page_test.js
  src/react/DeviceInterfaceValues.jsx
Labels: enhancement, testing

#229 Open groups modal when adding device to existing group
  cypress/integration/device_page_test.js
  src/elm/Page/Device.elm
Labels: bug

#220 Add typescript for Register Device page
  src/astarte-client/client.ts
  src/astarte-client/index.ts
  src/react/RegisterDevicePage.tsx
Labels: enhancement

#226 Add Cypress tests for interactions in Device page
  cypress/fixtures/device_detailed.json
  cypress/integration/device_page_test.js
  cypress/support/index.js
  cypress/support/websocket.js
  package-lock.json
  package.json
Labels: testing
