Repository astarte-platform/astarte-dashboard, pull requests merged in 2020-03, with the labels that each got.

#46 Fix babel and node 13.10.1 interaction
  package-lock.json
Labels: dependencies

#47 Paged devices
  CHANGELOG.md
  src/elm/Main.elm
  src/elm/Page/DeviceList.elm
  src/elm/Page/GroupDevices.elm
  src/elm/Page/ReactInit.elm
  src/react/AstarteClient.js
  src/react/DevicesPage.js
  src/react/GroupDevicesPage.js
  src/react/GroupsPage.js
  src/react/NewGroupPage.js
  src/react/Router.js
Labels: user experience

#48 Add device registration page
  CHANGELOG.md
  package-lock.json
  package.json
  src/elm/AstarteApi.elm
  src/elm/Main.elm
  src/elm/Route.elm
  src/react/AstarteClient.js
  src/react/Base64.js
  src/react/DevicesPage.js
  src/react/RegisterDevicePage.js
  src/react/Router.js
  src/react/astarte/Device.js
Labels: main feature

#50 Add wipe device credentials functionality
  CHANGELOG.md
  src/elm/AstarteApi.elm
  src/elm/Page/Device.elm
Labels: main feature

#55 Update dependencies with moderate vulnerabilities
  package-lock.json
  package.json
Labels: chore, dependencies

#56 Prepare v0.11.0-rc.1 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore
