Repository astarte-platform/astarte-dashboard, pull requests merged in 2020-08, with the labels that each got.

#136 InterfacesPage: Fix interface name max width
  src/react/InterfacesPage.js
Labels: minor

#137 Update dependencies to fix vulnerabilities
  package-lock.json
Labels: chore

#138 Add ignore_ssl_erros in HTTP trigger actions
  src/elm/Types/TriggerAction.elm
  src/elm/Ui/TriggerActionEditor.elm
Labels: enhancement

#128 Migrate login page to React
  src/elm/Main.elm
  src/elm/Page/Login.elm
  src/elm/Route.elm
  src/react/AstarteClient.js
  src/react/HomePage.js
  src/react/LoginPage.js
  src/react/Router.js
  src/static/index.js
Labels: chore

#140 Main.elm: fix re-login route
  src/elm/Main.elm
Labels: bug

#133 Add activity indicators
  src/react/FlowConfigurationPage.js
  src/react/FlowInstancesPage.js
  src/react/GroupDevicesPage.js
  src/react/NewGroupPage.js
  src/react/RealmSettingsPage.js
  src/react/RegisterDevicePage.js
Labels: enhancement

#139 Allow creation of pipelines with schema and their visualization
  package-lock.json
  package.json
  src/react/NewPipelinePage.js
  src/react/PipelineSourcePage.js
Labels: enhancement

#142 Bump version number to 0.11.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore

#141 Add alerts to the device group creation page
  src/react/NewGroupPage.js
Labels: enhancement

#145 Fix expiry measurement unit
  CHANGELOG.md
  package-lock.json
  package.json
  src/elm/Modal/MappingBuilder.elm
  src/elm/Page/InterfaceBuilder.elm
Labels: minor, user experience

#149 Fix webpack dependency vulnerability
  package-lock.json
  package.json
Labels: chore, dependencies
