Repository astarte-platform/astarte-dashboard, pull requests merged in 2020-09, with the labels that each got.

#146 Forwardport release 0.11
  CHANGELOG.md
  src/elm/Modal/MappingBuilder.elm
  src/elm/Page/InterfaceBuilder.elm
Labels: chore

#153 Encode group names when used in URLs
  src/elm/Route.elm
  src/react/AstarteClient.js
  src/react/GroupsPage.js
  src/react/Router.js
Labels: bug

#132 Add pages for Blocks
  src/elm/Icons.elm
  src/elm/Main.elm
  src/elm/Route.elm
  src/react/AstarteClient.js
  src/react/BlockSourcePage.js
  src/react/BlocksPage.js
  src/react/FlowInstancesPage.js
  src/react/NewBlockPage.js
  src/react/Router.js
  src/react/models/Block.js
  src/react/models/Model.js
Labels: main feature

#154 CheckableDeviceTable: rewrite using react hooks
  src/react/ui/CheckableDeviceTable.js
Labels: enhancement

#150 Add alerts to the device registration page
  src/react/RegisterDevicePage.js
  src/react/hooks/useRelativeTime.js
Labels: enhancement, user experience

#148 Add custom hooks for data fetching
  src/react/AstarteClient.js
  src/react/HomePage.js
  src/react/components/WaitForData.js
  src/react/hooks/useFetch.js
Labels: enhancement

#151 Add alerts to the Device interface data page
  src/react/DeviceInterfaceValues.js
Labels: enhancement, user experience

#155 Move Devices page to hooks
  src/react/DevicesPage.js
Labels: chore

#152 Improve expiry/ttl fields interaction
  src/elm/Modal/MappingBuilder.elm
  src/elm/Page/InterfaceBuilder.elm
Labels: user experience

#162 Fix build script error
  webpack.prod.js
Labels: blocking

#160 Add property unset event support
  CHANGELOG.md
  src/elm/Page/Device.elm
  src/elm/Types/DeviceEvent.elm
Labels: enhancement, user experience

#164 Remove remaining console.log
  src/react/DevicesPage.jsx
  src/react/GroupsPage.jsx
  src/static/index.js
Labels: chore

#159 Add typescript support
  .babelrc
  .eslintrc.json
  .github/workflows/code-quality.yml
  package-lock.json
  package.json
  src/react/Base64.ts
  tsconfig.json
  webpack.common.js
Labels: enhancement

#156 Initial implementation of pipeline visual editor
  CHANGELOG.md
  package-lock.json
  package.json
  src/react/NewPipelinePage.jsx
  src/react/components/NativeBlockFactory.jsx
  src/react/components/NativeBlockWidget.jsx
  src/react/components/VisualFlowEditor.jsx
  src/react/models/NativeBlockModel.js
  src/static/styles/flow-editor.scss
  src/static/styles/main.scss
Labels: enhancement, user experience

#166 Fix webpack config format and minimizer
  AUTHORS.md
  package-lock.json
  package.json
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: enhancement

#169 Add dashboard functionality tests
  .github/workflows/functionality-tests.yml
  cypress.json
  cypress/fixtures/realm.json
  cypress/integration/login_test.js
  package-lock.json
  package.json
  src/tools/generate-config-file.js
Labels: enhancement

#167 Add checks for code compilation process
  .github/workflows/code-quality.yml
Labels: enhancement

#173 Add tests for the interface list page
  cypress.json
  cypress/fixtures/interface_majors.json
  cypress/fixtures/interfaces.json
  cypress/integration/interfaces_page_test.js
  cypress/support/index.js
Labels: enhancement

#172 Fix device id string generation
  cypress/integration/base64_test.js
  src/react/Base64.ts
Labels: bug

#174 Fix sourcemap warnings with dev-server
  webpack.common.js
  webpack.dev.js
Labels: minor

#175 Add device registration tests
  cypress/integration/register_device_page_test.js
Labels: enhancement

#180 Bump version number to 0.11.3
  CHANGELOG.md
Labels: chore

#179 Device.elm: fix aggregate path format
  src/elm/Page/Device.elm
Labels: minor

#182 Add basic tests for page loading
  cypress/fixtures/test.astarte.FirstInterface.json
  cypress/fixtures/test.astarte.FirstTrigger.json
  cypress/fixtures/triggers.json
  cypress/integration/interface_builder_test.js
  cypress/integration/interfaces_page_test.js
  cypress/integration/register_device_page_test.js
  cypress/integration/trigger_builder_test.js
  cypress/integration/triggers_page_test.js
Labels: testing

#178 DeviceInterfaceValues: add parametric object datastreams
  CHANGELOG.md
  cypress/fixtures/device_detailed.json
  cypress/fixtures/test.astarte.ParametricObjectInterface.json
  cypress/fixtures/test_parametric_object_aggregated_values.json
  cypress/integration/interface_value_page_test.js
  src/react/DeviceInterfaceValues.jsx
Labels: minor
