Repository astarte-platform/astarte-dashboard, pull requests merged in 2020-02, with the labels that each got.

#22 DataTrigger.elm: init match path with /*
  CHANGELOG.md
  src/elm/Types/DataTrigger.elm
Labels: user experience

#20 Add "create new group" page
  CHANGELOG.md
  src/react/AstarteClient.js
  src/react/GroupsPage.js
  src/react/NewGroupPage.js
  src/react/astarte/Device.js
  src/react/ui/Card.js
  src/react/ui/CheckableDeviceTable.js
  src/static/index.js
Labels: main feature

#24 Remove device from group
  CHANGELOG.md
  src/react/AstarteClient.js
  src/react/GroupDevicesPage.js
  src/static/index.js
Labels: main feature

#26 Navbar color and layout restyle
  CHANGELOG.md
  package-lock.json
  package.json
  src/elm/Icons.elm
  src/elm/Main.elm
  src/static/img/logo.svg
  src/static/styles/main.scss
Labels: user experience

#29 Login layout rework
  src/elm/Assets.elm
  src/elm/Main.elm
  src/elm/Page/Login.elm
  src/static/img/background-login-bottom.svg
  src/static/img/background-login-top.svg
  src/static/img/logo-login.svg
  src/static/img/mascotte-computer.svg
  src/static/styles/main.scss
Labels: user experience

#31 index.js: fix channel template
  src/static/index.js
Labels: bug

#32 Update docker image nginx version
  CHANGELOG.md
  Dockerfile
Labels: dependencies

#36 Add database retention fields
  CHANGELOG.md
  src/elm/Modal/MappingBuilder.elm
  src/elm/Page/InterfaceBuilder.elm
  src/elm/Types/Interface.elm
  src/elm/Types/InterfaceMapping.elm
Labels: main feature

#33 Home page rework
  CHANGELOG.md
  elm.json
  src/elm/AstarteApi.elm
  src/elm/Icons.elm
  src/elm/Main.elm
  src/elm/Page/Home.elm
  src/elm/Ui/Card.elm
Labels: user experience

#37 InterfaceBuilder.elm: enable server owned aggregate objects
  CHANGELOG.md
  src/elm/Page/InterfaceBuilder.elm
Labels: blocking

#38 Interfaces and triggers list restyle
  src/elm/Page/Interfaces.elm
  src/elm/Page/Triggers.elm
Labels: user experience

#40 Device inhibit credentials
  CHANGELOG.md
  src/elm/AstarteApi.elm
  src/elm/Page/Device.elm
  src/elm/Types/Device.elm
Labels: blocking, main feature

#41 Device.elm: fix device stats table responsiveness
  src/elm/Page/Device.elm
Labels: user experience

#42 Prepare 0.11.0-rc.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore

#39 Uniform page titles style
  src/elm/Page/Device.elm
  src/elm/Page/DeviceData.elm
  src/elm/Page/DeviceList.elm
  src/elm/Page/InterfaceBuilder.elm
  src/elm/Page/RealmSettings.elm
  src/elm/Page/TriggerBuilder.elm
  src/react/GroupDevicesPage.js
  src/react/GroupsPage.js
  src/react/NewGroupPage.js
  src/react/ui/Card.js
  src/react/ui/SingleCardPage.js
Labels: user experience
