Repository astarte-platform/astarte-dashboard, pull requests merged in 2021-04, with the labels that each got.

#298 Update the README file
  README.md
Labels: documentation

#310 Fix titles and strings for buttons and modals
  CHANGELOG.md
  cypress/integration/block_page_test.js
  cypress/integration/device_page_test.js
  cypress/integration/flows_page_test.js
  cypress/integration/interface_builder_test.js
  cypress/integration/pipeline_page_test.js
  cypress/integration/trigger_builder_test.js
  src/elm/Modal/AskKeyValue.elm
  src/elm/Modal/AskSingleValue.elm
  src/elm/Modal/MappingBuilder.elm
  src/elm/Modal/SelectGroup.elm
  src/elm/Page/Device.elm
  src/elm/Page/InterfaceBuilder.elm
  src/elm/Page/TriggerBuilder.elm
  src/react/BlockSourcePage.tsx
  src/react/FlowInstancesPage.tsx
  src/react/HomePage.jsx
  src/react/PipelineSourcePage.tsx
Labels: user experience

#312 Forward port release-1.0 into master
  .env
  CHANGELOG.md
  README.md
  cypress/fixtures/device.json
  cypress/fixtures/device_detailed.json
  cypress/fixtures/devices_detailed.json
  cypress/fixtures/group.first-floor.devices.json
  cypress/fixtures/group.special-characters.devices.json
  cypress/fixtures/group.test-devices.devices.json
  cypress/integration/block_page_test.js
  cypress/integration/device_page_test.js
  cypress/integration/devices_page_test.js
  cypress/integration/flows_page_test.js
  cypress/integration/interface_builder_test.js
  cypress/integration/pipeline_page_test.js
  cypress/integration/trigger_builder_test.js
  src/App.tsx
  src/BlockSourcePage.tsx
  src/DeviceStatusPage/AddToGroupModal.tsx
  src/DeviceStatusPage/AliasesCard.tsx
  src/DeviceStatusPage/AttributesCard.tsx
  src/DeviceStatusPage/EditAliasModal.tsx
  src/DeviceStatusPage/EditAttributeModal.tsx
  src/DeviceStatusPage/NewAliasModal.tsx
  src/DeviceStatusPage/NewAttributeModal.tsx
  src/DeviceStatusPage/index.tsx
  src/DevicesPage.tsx
  src/FlowInstancesPage.tsx
  src/HomePage.tsx
  src/InterfacePage.tsx
  src/NewInterfacePage.tsx
  src/PipelineSourcePage.tsx
  src/Sidebar.tsx
  src/TriggerPage.tsx
  src/astarte-client/client.test.ts
  src/astarte-client/client.ts
  src/astarte-client/models/Device/index.ts
  src/astarte-client/transforms/device.ts
  src/astarte-client/types/dto/device.d.ts
  src/components/InterfaceEditor.tsx
  src/components/TriggerEditor/DeleteAmqpHeaderModal.tsx
  src/components/TriggerEditor/DeleteHttpHeaderModal.tsx
  src/components/TriggerEditor/EditAmqpHeaderModal.tsx
  src/components/TriggerEditor/EditHttpHeaderModal.tsx
  src/components/TriggerEditor/NewAmqpHeaderModal.tsx
  src/components/TriggerEditor/NewHttpHeaderModal.tsx
  src/components/TriggerEditor/TriggerActionForm.tsx
  src/components/TriggerEditor/index.tsx
  src/styles/main.scss
Labels: chore

#313 Fix Blocks sidebar menu overflowing Pipeline Editor
  src/static/styles/flow-editor.scss
Labels: minor

#311 Fix Eslint linting warnings
  src/AstarteManager.tsx
  src/ConfigManager.tsx
  src/DeviceStatusPage/DeviceLiveEventsCard.tsx
  src/DeviceStatusPage/PreviousInterfacesCard.tsx
  src/HomePage.tsx
  src/NewPipelinePage.tsx
  src/astarte-charts/providers/connectedDevices.ts
  src/astarte-client/client.ts
  src/astarte-client/models/Flow/index.ts
  src/astarte-client/models/Pipeline/index.ts
  src/astarte-client/transforms/device.ts
  src/astarte-client/types/dto/index.ts
  src/astarte-client/types/dto/trigger.d.ts
  src/astarte-client/types/events/AstarteDeviceConnectedEvent.ts
  src/astarte-client/types/events/AstarteDeviceDisconnectedEvent.ts
  src/astarte-client/types/events/AstarteDeviceErrorEvent.ts
  src/astarte-client/types/events/AstarteDeviceEvent.ts
  src/astarte-client/types/events/AstarteDeviceIncomingDataEvent.ts
  src/astarte-client/types/events/AstarteDeviceUnsetPropertyEvent.ts
  src/astarte-client/types/events/index.ts
  src/components/InterfaceEditor.tsx
  src/components/NativeBlockFactory.tsx
  src/components/NativeBlockWidget.tsx
  src/components/VisualFlowEditor.tsx
  src/components/WaitForData.ts
  src/components/modals/Form.tsx
  src/hooks/useFetch.ts
  src/models/NativeBlockModel.ts
  src/types/dashboardConfig.ts
Labels: chore

#308 Fix eslint warning on unused imports and exaustive dependencies
  src/AlertManager.tsx
  src/App.tsx
  src/BlockSourcePage.tsx
  src/DeviceStatusPage/DeviceLiveEventsCard.tsx
  src/DeviceStatusPage/ExchangedBytesCard.tsx
  src/DeviceStatusPage/index.tsx
  src/DevicesPage.tsx
  src/FlowConfigurationPage.tsx
  src/FlowInstancesPage.tsx
  src/GroupsPage.tsx
  src/InterfacePage.tsx
  src/NewBlockPage.tsx
  src/NewGroupPage.tsx
  src/NewInterfacePage.tsx
  src/NewPipelinePage.tsx
  src/NewTriggerPage.tsx
  src/PipelineSourcePage.tsx
  src/RealmSettingsPage.tsx
  src/RegisterDevicePage.tsx
  src/Sidebar.tsx
  src/TriggerPage.tsx
  src/components/InterfaceEditor.tsx
  src/components/TriggerEditor/SimpleTriggerForm.tsx
  src/components/TriggerEditor/index.tsx
  src/components/VisualFlowEditor.tsx
  src/components/modals/Confirm.tsx
Labels: enhancement

#307 Add Redux state management
  .eslintrc.json
  package-lock.json
  package.json
  src/App.tsx
  src/BlockSourcePage.tsx
  src/BlocksPage.tsx
  src/NewBlockPage.tsx
  src/components/WaitForData.ts
  src/store/actions.ts
  src/store/index.ts
  src/store/selectors.ts
  src/store/slices/blocks.ts
  src/store/slices/index.ts
Labels: enhancement

#314 Forward port release-1.0 into master
  src/styles/flow-editor.scss
Labels: chore
