Repository astarte-platform/astarte-dashboard, pull requests merged in 2021-03, with the labels that each got.

#296 Test build process in different environments
  .github/workflows/build-compatibility.yml
  .github/workflows/docker-build.yml
  .github/workflows/functionality-tests.yml
Labels: testing

#276 Port Trigger Editor from Elm to React
  CHANGELOG.md
  cypress/integration/trigger_builder_test.js
  src/astarte-client/client.ts
  src/astarte-client/index.ts
  src/astarte-client/models/Interface/index.ts
  src/astarte-client/models/Mapping/index.ts
  src/astarte-client/models/Trigger/index.ts
  src/astarte-client/models/index.ts
  src/astarte-client/transforms/index.ts
  src/astarte-client/transforms/trigger.ts
  src/astarte-client/types/dto/index.ts
  src/astarte-client/types/dto/trigger.d.ts
  src/elm/AstarteApi.elm
  src/elm/HtmlUtils.elm
  src/elm/Main.elm
  src/elm/Modal/AskKeyValue.elm
  src/elm/Modal/AskSingleValue.elm
  src/elm/Modal/ConfirmModal.elm
  src/elm/Page/TriggerBuilder.elm
  src/elm/Types/DataTrigger.elm
  src/elm/Types/DeviceTrigger.elm
  src/elm/Types/Interface.elm
  src/elm/Types/InterfaceMapping.elm
  src/elm/Types/SuggestionPopup.elm
  src/elm/Types/Trigger.elm
  src/elm/Types/TriggerAction.elm
  src/elm/Ui/Card.elm
  src/elm/Ui/TriggerActionEditor.elm
  src/react/NewTriggerPage.tsx
  src/react/Router.tsx
  src/react/TriggerPage.tsx
  src/react/components/TriggerEditor/EditAmqpHeaderModal.tsx
  src/react/components/TriggerEditor/EditHttpHeaderModal.tsx
  src/react/components/TriggerEditor/NewAmqpHeaderModal.tsx
  src/react/components/TriggerEditor/NewHttpHeaderModal.tsx
  src/react/components/TriggerEditor/RemoveAmqpHeaderModal.tsx
  src/react/components/TriggerEditor/RemoveHttpHeaderModal.tsx
  src/react/components/TriggerEditor/SimpleTriggerForm.tsx
  src/react/components/TriggerEditor/TriggerActionForm.tsx
  src/react/components/TriggerEditor/index.tsx
Labels: main feature

#294 Add missing fallbacks for loading errors in pages
  src/react/DeviceStatusPage/index.tsx
  src/react/InterfacePage.tsx
Labels: enhancement

#297 Add Remove icon for Pipeline Editor blocks
  src/react/components/NativeBlockFactory.tsx
  src/react/components/NativeBlockWidget.tsx
  src/react/components/VisualFlowEditor.tsx
  src/react/models/NativeBlockModel.ts
  src/static/styles/flow-editor.scss
Labels: enhancement

#299 Add reusable Icon component
  cypress/integration/devices_page_test.js
  src/react/App.tsx
  src/react/DeviceStatusPage/AddToGroupModal.tsx
  src/react/DeviceStatusPage/AliasesCard.tsx
  src/react/DeviceStatusPage/DeviceInfoCard.tsx
  src/react/DeviceStatusPage/MetadataCard.tsx
  src/react/DevicesPage.tsx
  src/react/FlowInstancesPage.tsx
  src/react/GroupDevicesPage.tsx
  src/react/HomePage.tsx
  src/react/InterfacesPage.tsx
  src/react/NewGroupPage.tsx
  src/react/RegisterDevicePage.tsx
  src/react/Sidebar.tsx
  src/react/TriggersPage.tsx
  src/react/components/Icon.tsx
  src/react/components/InterfaceEditor.tsx
  src/react/components/NativeBlockWidget.tsx
  src/react/components/TriggerEditor/TriggerActionForm.tsx
  src/react/ui/BackButton.tsx
  src/react/ui/SingleCardPage.tsx
  src/static/styles/main.scss
Labels: enhancement

#302 Fix OAuth login form
  cypress/fixtures/config/multiple_auth.json
  cypress/fixtures/config/oauth.json
  cypress/integration/login_test.js
  src/react/LoginPage.tsx
  src/react/Router.jsx
  src/static/index.js
Labels: bug

#285 Add support for filter params when fetching devices data
  cypress/fixtures/test_aggregated_object_interface_linearized_values.json
  cypress/fixtures/test_individual_object_interface_linearized_values.json
  cypress/fixtures/test_individual_object_interface_path_values.json
  cypress/fixtures/test_properties_interface_linearized_values.json
  cypress/integration/astarte_client.js
  src/astarte-client/client.test.ts
  src/astarte-client/client.ts
  src/astarte-client/transforms/dataTree.test.ts
  src/astarte-client/transforms/dataTree.ts
  src/astarte-client/types/interfaceValues.ts
Labels: enhancement

#304 Forward port release-1.0 into master
  .github/workflows/build-compatibility.yml
  .github/workflows/docker-build.yml
  .github/workflows/functionality-tests.yml
  Dockerfile
  cypress/fixtures/config/multiple_auth.json
  cypress/fixtures/config/oauth.json
  cypress/integration/login_test.js
  package.json
  src/ConfigManager.tsx
  src/LoginPage.tsx
  src/Router.tsx
  src/components/NativeBlockFactory.tsx
  src/components/NativeBlockWidget.tsx
  src/components/VisualFlowEditor.tsx
  src/models/NativeBlockModel.ts
  src/styles/flow-editor.scss
  src/types/dashboardConfig.ts
Labels: chore

#306 Prepare v1.0.0-beta.2
  CHANGELOG.md
Labels: chore

#309 Add Astarte Dashboard version in the navigation menu
  CHANGELOG.md
  package-lock.json
  package.json
  src/elm/Main.elm
  src/static/index.js
  src/static/styles/main.scss
  webpack.common.js
Labels: user experience
