Repository astarte-platform/astarte-dashboard, pull requests merged in 2021-02, with the labels that each got.

#280 Add support for native Blocks in the Pipeline Editor
  cypress/integration/new_pipeline_page_test.js
  src/astarte-client/client.ts
  src/astarte-client/definitions/blocks/astarte_devices_source.json
  src/astarte-client/definitions/blocks/container.json
  src/astarte-client/definitions/blocks/dynamic_virtual_device_pool.json
  src/astarte-client/definitions/blocks/index.ts
  src/astarte-client/definitions/blocks/split_map.json
  src/astarte-client/definitions/blocks/virtual_device_pool.json
  src/astarte-client/definitions/index.ts
  src/react/NewPipelinePage.tsx
  src/react/components/NativeBlockFactory.tsx
  src/react/components/VisualFlowEditor.tsx
  src/react/models/NativeBlockModel.ts
  src/react/ui/SingleCardPage.tsx
Labels: enhancement

#281 Fix virtual_device_pool's JSON Schema
  src/astarte-client/definitions/blocks/virtual_device_pool.json
Labels: bug

#271 Change Flow routes to avoid possible conflicting routes
  CHANGELOG.md
  cypress/integration/block_page_test.js
  cypress/integration/blocks_page_test.js
  cypress/integration/flow_page_test.js
  cypress/integration/flows_page_test.js
  cypress/integration/new_block_page_test.js
  cypress/integration/new_flow_page_test.js
  cypress/integration/new_pipeline_page_test.js
  cypress/integration/pipeline_page_test.js
  cypress/integration/pipelines_page_test.js
  src/elm/Route.elm
  src/react/BlocksPage.tsx
  src/react/FlowInstancesPage.tsx
  src/react/NewBlockPage.tsx
  src/react/NewPipelinePage.tsx
  src/react/PipelinesPage.tsx
  src/react/Router.jsx
Labels: bug

#273 Limit triggers type for object interfaces
  CHANGELOG.md
  package-lock.json
  package.json
  src/elm/Page/TriggerBuilder.elm
Labels: bug

#274 Support target device or group in data triggers
  CHANGELOG.md
  src/elm/Page/TriggerBuilder.elm
  src/elm/Types/DataTrigger.elm
Labels: enhancement

#282 Fix validation of database_retention_ttl in blocks schema
  src/astarte-client/definitions/blocks/dynamic_virtual_device_pool.json
  src/astarte-client/definitions/blocks/virtual_device_pool.json
Labels: bug

#283 Fix broken links for triggers and interfaces
  cypress/integration/interfaces_page_test.js
  cypress/integration/triggers_page_test.js
  src/react/InterfacesPage.tsx
  src/react/TriggersPage.tsx
Labels: minor

#278 Forward port release-1.0 into master
  CHANGELOG.md
  cypress/integration/device_page_test.js
  cypress/integration/devices_page_test.js
  cypress/integration/group_page_test.js
  cypress/integration/groups_page_test.js
  cypress/integration/home_page_test.js
  cypress/integration/interface_builder_test.js
  cypress/integration/trigger_builder_test.js
  src/elm/Main.elm
  src/elm/Route.elm
  src/react/DeviceStatusPage/GroupsCard.tsx
  src/react/DevicesPage.tsx
  src/react/GroupDevicesPage.tsx
  src/react/GroupsPage.tsx
  src/react/HomePage.jsx
  src/react/Router.jsx
Labels: chore

#286 Forward port release-0.11 into release-1.0
  CHANGELOG.md
  src/elm/Page/TriggerBuilder.elm
Labels: chore

#288 Forward port release-1.0 into master
  CHANGELOG.md
  cypress/integration/block_page_test.js
  cypress/integration/blocks_page_test.js
  cypress/integration/flow_page_test.js
  cypress/integration/flows_page_test.js
  cypress/integration/interfaces_page_test.js
  cypress/integration/new_block_page_test.js
  cypress/integration/new_flow_page_test.js
  cypress/integration/new_pipeline_page_test.js
  cypress/integration/pipeline_page_test.js
  cypress/integration/pipelines_page_test.js
  cypress/integration/triggers_page_test.js
  src/astarte-client/client.ts
  src/astarte-client/definitions/blocks/astarte_devices_source.json
  src/astarte-client/definitions/blocks/container.json
  src/astarte-client/definitions/blocks/dynamic_virtual_device_pool.json
  src/astarte-client/definitions/blocks/index.ts
  src/astarte-client/definitions/blocks/split_map.json
  src/astarte-client/definitions/blocks/virtual_device_pool.json
  src/astarte-client/definitions/index.ts
  src/elm/Page/TriggerBuilder.elm
  src/elm/Route.elm
  src/elm/Types/DataTrigger.elm
  src/react/BlocksPage.tsx
  src/react/FlowInstancesPage.tsx
  src/react/InterfacesPage.tsx
  src/react/NewBlockPage.tsx
  src/react/NewPipelinePage.tsx
  src/react/PipelinesPage.tsx
  src/react/Router.jsx
  src/react/TriggersPage.tsx
  src/react/components/NativeBlockFactory.tsx
  src/react/components/VisualFlowEditor.tsx
  src/react/models/NativeBlockModel.ts
  src/react/ui/SingleCardPage.tsx
Labels: chore

#265 Add more specific Cypress tests for the Trigger Builder
  cypress/fixtures/test.astarte.FirstTrigger.json
  cypress/integration/trigger_builder_test.js
  src/elm/Page/TriggerBuilder.elm
Labels: testing

#279 Enhance usage of Cypress methods
  cypress/integration/block_page_test.js
  cypress/integration/blocks_page_test.js
  cypress/integration/device_page_test.js
  cypress/integration/devices_page_test.js
  cypress/integration/flow_page_test.js
  cypress/integration/flows_page_test.js
  cypress/integration/group_page_test.js
  cypress/integration/groups_page_test.js
  cypress/integration/home_page_test.js
  cypress/integration/interface_builder_test.js
  cypress/integration/interface_value_page_test.js
  cypress/integration/interfaces_page_test.js
  cypress/integration/login_test.js
  cypress/integration/new_block_page_test.js
  cypress/integration/new_flow_page_test.js
  cypress/integration/new_group_page.js
  cypress/integration/new_pipeline_page_test.js
  cypress/integration/pipeline_page_test.js
  cypress/integration/pipelines_page_test.js
  cypress/integration/realm_settings_page_test.js
  cypress/integration/register_device_page_test.js
  cypress/integration/sidebar_test.js
  cypress/integration/trigger_builder_test.js
  cypress/integration/triggers_page_test.js
  cypress/support/index.js
  src/elm/Page/InterfaceBuilder.elm
Labels: testing

#289 Update NPM dependencies
  package-lock.json
  package.json
  src/astarte-client/models/Realm/index.ts
  src/astarte-client/transforms/pipeline.ts
  src/react/components/modals/Form.tsx
Labels: chore

#290 Fix login layout on small screen devices
  CHANGELOG.md
  package-lock.json
  package.json
  src/react/LoginPage.tsx
Labels: user experience

#291 Fix back button on device interface values page
  cypress/integration/interface_value_page_test.js
  src/react/DeviceInterfaceValues.jsx
  src/react/ui/BackButton.tsx
Labels: minor

#292 Downgrade react to 16.14.0
  package-lock.json
  package.json
Labels: dependencies

#293 Forward port release-1.0 into master
  CHANGELOG.md
  cypress/fixtures/test.astarte.FirstTrigger.json
  cypress/integration/block_page_test.js
  cypress/integration/blocks_page_test.js
  cypress/integration/device_page_test.js
  cypress/integration/devices_page_test.js
  cypress/integration/flow_page_test.js
  cypress/integration/flows_page_test.js
  cypress/integration/group_page_test.js
  cypress/integration/groups_page_test.js
  cypress/integration/home_page_test.js
  cypress/integration/interface_builder_test.js
  cypress/integration/interface_value_page_test.js
  cypress/integration/interfaces_page_test.js
  cypress/integration/login_test.js
  cypress/integration/new_block_page_test.js
  cypress/integration/new_flow_page_test.js
  cypress/integration/new_group_page.js
  cypress/integration/new_pipeline_page_test.js
  cypress/integration/pipeline_page_test.js
  cypress/integration/pipelines_page_test.js
  cypress/integration/realm_settings_page_test.js
  cypress/integration/register_device_page_test.js
  cypress/integration/sidebar_test.js
  cypress/integration/trigger_builder_test.js
  cypress/integration/triggers_page_test.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/astarte-charts/index.ts
  src/astarte-client/models/Mapping/index.ts
  src/astarte-client/models/Realm/index.ts
  src/astarte-client/transforms/device.ts
  src/astarte-client/transforms/interface.ts
  src/astarte-client/transforms/mapping.ts
  src/astarte-client/transforms/pipeline.ts
  src/elm/Page/TriggerBuilder.elm
  src/react/DeviceInterfaceValues.tsx
  src/react/DeviceStatusPage/AliasesCard.tsx
  src/react/DeviceStatusPage/DeviceInfoCard.tsx
  src/react/DeviceStatusPage/DeviceLiveEventsCard.tsx
  src/react/DeviceStatusPage/GroupsCard.tsx
  src/react/DeviceStatusPage/MetadataCard.tsx
  src/react/DeviceStatusPage/PreviousInterfacesCard.tsx
  src/react/InterfaceEditorPage.tsx
  src/react/LoginPage.tsx
  src/react/NewInterfacePage.tsx
  src/react/components/InterfaceEditor.tsx
  src/react/components/modals/Form.tsx
  src/react/ui/BackButton.tsx
Labels: chore
