Repository astarte-platform/astarte-dashboard, pull requests merged in 2021-01, with the labels that each got.

#260 Update dependencies to fix high risk vurnerabilities
  package-lock.json
  package.json
  src/react/AstarteClient.js
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: chore

#262 Forward port release 0.11 into release 1.0
  CHANGELOG.md
  cypress/integration/realm_settings_page_test.js
  package-lock.json
  package.json
  src/elm/Page/Device.elm
  src/elm/Page/TriggerBuilder.elm
  src/elm/Types/Interface.elm
  src/static/styles/main.scss
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: chore

#263 BlocksPage: fix typo
  src/react/BlocksPage.tsx
Labels: user experience

#257 Show navbar when in standalone Interface Editor mode
  cypress/integration/interface_builder_test.js
  src/elm/Main.elm
Labels: minor

#232 Move New Interface page from Elm to React
  CHANGELOG.md
  cypress/fixtures/test.astarte.NoDefaultsInterface.json
  cypress/fixtures/test.astarte.SpecifiedDefaultsInterface.json
  cypress/integration/interface_builder_test.js
  elm.json
  src/astarte-client/client.ts
  src/astarte-client/transforms/interface.ts
  src/astarte-client/types/dto/interface.d.ts
  src/elm/Main.elm
  src/elm/Modal/MappingBuilder.elm
  src/elm/Page/InterfaceBuilder.elm
  src/elm/Types/InterfaceMapping.elm
  src/react/NewInterfacePage.tsx
  src/react/Router.jsx
  src/react/components/InterfaceEditor.tsx
  src/react/components/MappingEditor.tsx
  src/static/styles/main.scss
Labels: enhancement

#236 Add Astarte Charts
  CHANGELOG.md
  cypress/integration/device_page_test.js
  src/astarte-charts/dataKinds/Aggregated.ts
  src/astarte-charts/dataKinds/ConnectedDevices.ts
  src/astarte-charts/dataKinds/DeviceStats.ts
  src/astarte-charts/dataKinds/TimestampedAggregated.ts
  src/astarte-charts/dataKinds/TimestampedIndividual.ts
  src/astarte-charts/dataKinds/index.ts
  src/astarte-charts/index.ts
  src/astarte-charts/providers/connectedDevices.ts
  src/astarte-charts/providers/deviceDatastreamIndividual.ts
  src/astarte-charts/providers/deviceDatastreamObject.ts
  src/astarte-charts/providers/deviceProperty.ts
  src/astarte-charts/providers/deviceStats.ts
  src/astarte-charts/providers/index.ts
  src/astarte-charts/providers/provider.ts
  src/astarte-charts/react/ConnectedDevices/index.tsx
  src/astarte-charts/react/PieChart/index.tsx
  src/astarte-charts/react/TimeseriesChart/index.tsx
  src/astarte-charts/react/hooks/index.ts
  src/astarte-charts/react/hooks/useChartProviders.ts
  src/astarte-charts/react/index.ts
  src/react/DeviceStatusPage/DeviceDataPieChart.tsx
  src/react/DeviceStatusPage/ExchangedBytesCard.tsx
  src/react/DeviceStatusPage/index.tsx
  src/react/HomePage.jsx
  src/react/ui/DevicesPieChart.jsx
  src/static/styles/main.scss
  tsconfig.json
  webpack.common.js
Labels: enhancement

#233 Port Interface page from Elm to React
  cypress/integration/interface_builder_test.js
  src/astarte-client/client.ts
  src/elm/Main.elm
  src/react/InterfacePage.tsx
  src/react/Router.jsx
  src/react/components/InterfaceEditor.tsx
  src/react/components/modals/Confirm.tsx
Labels: enhancement

#250 Invite device registration after wiping credentials in DevicePage
  cypress/integration/device_page_test.js
  src/elm/Main.elm
  src/elm/Modal/ConfirmModal.elm
  src/elm/Page/Device.elm
  src/elm/Page/TriggerBuilder.elm
  src/elm/Route.elm
  src/react/RegisterDevicePage.tsx
  src/react/Router.jsx
Labels: user experience

#244 Add Typescript to SessionManager
  package-lock.json
  package.json
  src/react/Router.jsx
  src/react/SessionManager.js
  src/react/SessionManager.ts
  src/static/index.js
Labels: enhancement

#266 Fix typos in Trigger Editor
  CHANGELOG.md
  src/elm/Page/TriggerBuilder.elm
Labels: minor

#258 Add React standalone Interface Editor
  src/elm/AstarteApi.elm
  src/elm/Main.elm
  src/elm/Modal/MappingBuilder.elm
  src/elm/Page/InterfaceBuilder.elm
  src/react/InterfaceEditorPage.tsx
  src/react/Router.jsx
  src/react/components/InterfaceEditor.tsx
  src/static/index.js
Labels: enhancement

#267 Forward port release 1.0
  CHANGELOG.md
  cypress/integration/device_page_test.js
  cypress/integration/group_page_test.js
  cypress/integration/interface_builder_test.js
  cypress/integration/realm_settings_page_test.js
  package-lock.json
  package.json
  src/astarte-client/client.ts
  src/elm/AstarteApi.elm
  src/elm/Main.elm
  src/elm/Modal/ConfirmModal.elm
  src/elm/Page/TriggerBuilder.elm
  src/elm/Route.elm
  src/elm/Types/Interface.elm
  src/react/BlocksPage.tsx
  src/react/DeviceStatusPage/index.tsx
  src/react/RealmSettingsPage.tsx
  src/react/RegisterDevicePage.tsx
  src/react/Router.jsx
  src/static/styles/main.scss
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: chore

#247 Enhance content loading on React pages
  cypress/integration/blocks_page_test.js
  cypress/integration/interface_value_page_test.js
  src/astarte-client/client.ts
  src/react/BlockSourcePage.tsx
  src/react/BlocksPage.tsx
  src/react/DeviceInterfaceValues.tsx
  src/react/DevicesPage.tsx
  src/react/FlowDetailsPage.tsx
  src/react/FlowInstancesPage.tsx
  src/react/GroupDevicesPage.tsx
  src/react/GroupsPage.tsx
  src/react/InterfacesPage.tsx
  src/react/NewGroupPage.tsx
  src/react/PipelineSourcePage.tsx
  src/react/PipelinesPage.tsx
  src/react/RealmSettingsPage.tsx
  src/react/TriggersPage.tsx
  src/react/components/Empty.tsx
  src/react/hooks/useFetch.ts
  src/static/img/mascotte-repair.svg
Labels: enhancement

#268 consider ValueChange triggers on path /* as invalid
  CHANGELOG.md
  src/elm/Page/TriggerBuilder.elm
Labels: user experience

#270 Change /resource/:id routes to avoid conflicts with /resource/new
  CHANGELOG.md
  src/elm/Route.elm
  src/react/GroupDevicesPage.js
  src/react/GroupsPage.js
  src/react/Router.js
Labels: bug

#272 Prepare v0.11.4 release
  CHANGELOG.md
Labels: chore

#275 Forward port release-0.11 into release-1.0
  CHANGELOG.md
  cypress/integration/device_page_test.js
  cypress/integration/devices_page_test.js
  cypress/integration/group_page_test.js
  cypress/integration/groups_page_test.js
  cypress/integration/home_page_test.js
  cypress/integration/interface_builder_test.js
  cypress/integration/trigger_builder_test.js
  src/elm/Main.elm
  src/elm/Route.elm
  src/react/DevicesPage.tsx
  src/react/GroupDevicesPage.tsx
  src/react/GroupsPage.tsx
  src/react/HomePage.jsx
  src/react/Router.jsx
Labels: chore
